@startuml sequence

    skinparam actorStyle awesome
    
    actor "Joueur" as J order 1
    participant "Système" as S order 2
    actor "Maitre de jeu" as MJ order 3

    == Création de personnage ==
    J --> S : Saisit les informations du personnage
    S --> J : Confirme la création
    J -> S : Propose le personnage au MJ
    S -> MJ : Notifie la proposition de personnage
    MJ --> S : Consulte les informations du personnage
    MJ -> S : Accepte/rejette le personnage
    S --> J : Notifie la décision du MJ

newpage

    == Publication d'épisode par le Maitre du jeu==
    MJ -> S : Créé un épisode brouillon
    MJ --> S : Modifie/sauvegarde le brouillon
    MJ -> S : Soumet l'épisode au joueur
    S -> J : Notifie la soumission d'épisode
    J -> S : Consulte l'épisode
    J -> S : Accepte/rejette l'épisode
    S --> MJ : Notifie la décision du joueur
    MJ -> J : Publie l'épisode
    J -> J : Consulte l'épisode publié

    == Publication d'épisode par le Joueur ==
    J -> S : Créé un épisode brouillon
    J --> S : Modifie/sauvegarde le brouillon
    J -> S : Soumet l'épisode au MJ
    S -> MJ : Notifie la soumission d'épisode
    MJ -> S : Consulte l'épisode
    MJ -> S : Accepte/rejette l'épisode
    S --> J : Notifie la décision du MJ
    J --> S : Consulte l'épisode publié




newpage
    
    == Transfert de MJ ==
    J -> S : Demande le transfert de MJ
    S -> S : Verifie les conditions de transfert
    S -> MJ : Notifie la demande de transfert
    MJ -> J : Accepte/rejette le transfert de MJ

newpage

    actor "Joueur" as J
    actor "Maitre de jeu" as MJ

    == Création de partie ==
    MJ -> MJ : Rédige une proposition de partie
    MJ -> J : Propose la partie
    MJ -> MJ : Ajoute les personnages des joueurs à la partie

    MJ --> MJ : Supprime la proposition de partie


@enduml